// Code generated by command: go run avo.go -out ../../asm_amd64.s -stubs ../../stubs_amd64.go -pkg vectorcmp --dispatcher-amd64 ../../dispatch_amd64.go --dispatcher-other ../../dispatch_other.go. DO NOT EDIT.

//go:build !purego

package vectorcmp

//go:noescape
func asmAVX2Equals8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVXEquals8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVX2GreaterThan8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVXGreaterThan8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVX2LessThan8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVXLessThan8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVX2GreaterEquals8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVXGreaterEquals8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVX2LesserEquals8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVXLesserEquals8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmAVX2Equals16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVXEquals16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVX2GreaterThan16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVXGreaterThan16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVX2LessThan16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVXLessThan16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVX2GreaterEquals16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVXGreaterEquals16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVX2LesserEquals16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVXLesserEquals16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmAVX2Equals32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVXEquals32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVX2GreaterThan32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVXGreaterThan32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVX2LessThan32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVXLessThan32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVX2GreaterEquals32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVXGreaterEquals32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVX2LesserEquals32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVXLesserEquals32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmAVX2Equals64(dstMask []byte, b uint64, rows []uint64)

//go:noescape
func asmAVX2GreaterThan64(dstMask []byte, b uint64, rows []uint64)

//go:noescape
func asmAVX2LessThan64(dstMask []byte, b uint64, rows []uint64)

//go:noescape
func asmAVX2GreaterEquals64(dstMask []byte, b uint64, rows []uint64)

//go:noescape
func asmAVX2LesserEquals64(dstMask []byte, b uint64, rows []uint64)
