// Code generated by command: go run avo.go -out ../../asm_amd64.s -stubs ../../stubs_amd64.go -pkg vectorcmp --dispatcher-amd64 ../../dispatch_amd64.go --dispatcher-other ../../dispatch_other.go. DO NOT EDIT.

//go:build !purego

package vectorcmp

//go:noescape
func asmBulkEquals8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmBulkGreaterThan8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmBulkLessThan8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmBulkGreaterEquals8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmBulkLesserEquals8(dstMask []byte, b uint8, rows []uint8)

//go:noescape
func asmBulkEquals16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmBulkGreaterThan16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmBulkLessThan16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmBulkGreaterEquals16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmBulkLesserEquals16(dstMask []byte, b uint16, rows []uint16)

//go:noescape
func asmBulkEquals32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmBulkGreaterThan32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmBulkLessThan32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmBulkGreaterEquals32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmBulkLesserEquals32(dstMask []byte, b uint32, rows []uint32)

//go:noescape
func asmBulkEquals64(dstMask []byte, b uint64, rows []uint64)

//go:noescape
func asmBulkGreaterThan64(dstMask []byte, b uint64, rows []uint64)

//go:noescape
func asmBulkLessThan64(dstMask []byte, b uint64, rows []uint64)

//go:noescape
func asmBulkGreaterEquals64(dstMask []byte, b uint64, rows []uint64)

//go:noescape
func asmBulkLesserEquals64(dstMask []byte, b uint64, rows []uint64)
